import { Roboto_Flex } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";

const robotoFlex = Roboto_Flex({ subsets: ["latin"], display: 'swap' });

export const metadata = {
  title: "Example Frontend",
  description: "Generated by Full Stack Developer",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={robotoFlex.className}>
        <header>
          <Header />
        </header>
        <main>
          {children}
        </main>
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
