##############################
###### GENERAL SETTINGS ######
##############################
server:
  port: ${SERVER_PORT}
  error:
    include-message: always
    include-stacktrace: never
  servlet:
    context-path: ${SERVER_SERVLET_CONTEXT_PATH}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${SPRING_APPLICATION_NAME}
    error-uri: /error
  config:
    import:
      - optional:file:.env[.properties]
      - application-database.yml
      - application-security.yml

##############################
######### I18N CONFIG ########
##############################
  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: 60
    fallback-to-system-locale: false

##############################
#### SPRING DEBUG SETTING ####
##############################
logging:
  language: ${LOGGING_LANGUAGE}
  level:
    root: info
    org.springframework.web: ERROR
